# Generated by Django 3.0.3 on 2020-08-17 10:57

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('PLUMBING', 'PLUMBING'), ('ELECTRICAL', 'ELECTRICAL'), ('PAINTING', 'PAINTING'), ('DEEPCLEANING', 'DEEPCLEANING')], max_length=255)),
                ('request_desc', models.CharField(max_length=100)),
                ('request_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('inprogress', 'inprogress'), ('completed', 'completed')], max_length=255)),
                ('state', models.CharField(choices=[('AndhraPradesh', 'AndhraPradesh'), ('ArunachalPradesh', 'ArunachalPradesh'), ('Pune', 'Pune')], max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
            ],
        ),
    ]
